### ISSUE TITLE
Selection стили для кода

### ISSUE THREAD

**Issue by vaiil** [risenforces/risen.dev#4]
Добрый день, во время чтения [статьи](https://risen.dev/posts/js-in-details-part-1/) возникает желание скопировать блок инлайн-кода (различного рода понятия) и поискать их в спеке. Из-за следующих стилей выделение данных блоков текста не очевидно:
```css
code[class*=language-]::selection, code[class*=language-] ::selection, pre[class*=language-]::selection, pre[class*=language-] ::selection {
    text-shadow: none;
    background: hsla(0,0%,100%,.1);
}
``` 
Данные стили используются для более красивого выделения в многострочных блоках кода, но они сбрасывают визуальное представление выделения на инлайновых блоках. Возможно стоит оставить только стили для pre?
